name: Test action
on:
  workflow_dispatch:
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: jupyter/pyspark-notebook
    steps:
    - name: ran in container
      run: |
        ls
        echo Hello