name: Test action
on:
  workflow_dispatch:
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: jupyter/pyspark-notebook
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Create virtual environment
      run: |
        python3 -m venv .venv
    - name: Activate virtual environment
      run: |
        source .venv/bin/activate
    - name: Install package
      run: |
        pip install -e .[dev]
    - name: Run unit tests
      run: |
        pytest