name: Test action
on:
  workflow_dispatch:
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: jupyter/pyspark-notebook
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Install package with dev dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv .venv